---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluentinc
  install: {}
  interval: 1m0s
  values:
    replicas: 1
    namespaced: false
    telemetry:
      enabled: true
      secretRef: cloud-key
      


